### ISSUE TITLE
TypeError: Data location must be "storage" or "memory" for parameter in function, but none was given.

### ISSUE THREAD

**Issue by cspartho** [dappuniversity/election#19]
function addCandidate (string _name) private {
        candidatesCount ++;
        candidates[candidatesCount] = Candidate(candidatesCount, _name, 0);
    }
there is an error on string _name.the compiler says data location must be storage or memory.how to fix it?

**Comment by malavancs** [comment]
I'm still getting the same error what should i do ?

**Comment by IndumathiMadhu** [comment]
You need to specify whether your arrays parameters are memory or storage. 
Change the signature of addCandidate (string _name) to addCandidate (string memory _name).

It worked for me
