### ISSUE TITLE
Getcoinbase return null as account using metamask

### ISSUE THREAD

**Issue by manishsingh10895** [dappuniversity/election#26]
web3.eth.getCoinbase function returns account as null always when using metamask eth Provider, while using http provider using ganache works perfectly.

**Metamask version 6.7.2**

**Comment by faruk13** [comment]
Even I stumbled upon this problem, do one thing go to metamask settings and switch off the privacy mode.
Check out this Eth StackExchange answer https://ethereum.stackexchange.com/a/69914/47797

**Comment by digu-007** [comment]
> switch off the privacy mode.

@faruk13 There is no privacy mode in the settings, what should I do?

**Comment by SHIVANGISINGH1** [comment]
Connecting to the site localhost:3000 manually from metamask worked for me.

**Comment by manishsingh10895** [comment]
Closing this issue, as it is opened for too long and metamask and web3 apis have major changes.
